// export interface CompanySearch {
//     Currency: string;
//     ExchangeShortName: string;
//     Name: string;
//     StockExchange: string;
//     Symbol: string;
// }

// export interface CompanyProfile {
//     Symbol: string;
//     Price: number;
//     Beta: number;
//     VolAvg: number;
//     MktCap: number;
//     LastDiv: number;
//     Range: string;
//     Changes: number;
//     CompanyName: string;
//     Currency: string;
//     Cik: string;
//     Isin: string;
//     Exchange: string;
//     ExchangeShortName: string;
//     Industry: string;
//     Website: string;
//     Description: string;
//     Ceo: string;
//     Sector: string;
//     Counter: string;
//     FullTimeEmployees: string;
//     Phone: string;
//     Address: string;
//     City: string;
//     State: string;
//     Zip: string;
//     DcfDiff: number;
//     Dcf: number;
//     Image: string;
//     IpoDate: string;
//     DefaultImage: boolean;
//     IsEtf: boolean;
//     IsActivelyTrading: boolean;
//     IsAdr: boolean;
//     IsFund: boolean;
// }

// export interface CompanyKeyRatios {
//     DividendYielTTM: number;
//     DividendYielPercentageTTM: number;
//     PeRatioTTM: number;
//     PegRatioTTM: number;
//     PayoutRatioTTM: number;
//     CurrentRatioTTM: number;
//     QuickRatioTTM: number;
//     CashRatioTTM: number;
//     DaysOfSalesOutstandingTTM: number;
//     DaysOfInventoryOutstandingTTM: number;
//     OperatingCycleTTM: number;
//     DaysOfPayablesOutstandingTTM: number;
//     CashConversionCycleTTM: number;
//     GrossProfitMarginTTM: number;
//     OperatingProfitMarginTTM: number;
//     PretaxProfitMarginTTM: number;
//     NetProfitMarginTTM: number;
//     EffectiveTaxRateTTM: number;
//     ReturnOnAssetsTTM: number;
//     ReturnOnEquityTTM: number;
//     ReturnOnCapitalEmployedTTM: number;
//     NetIncomePerEBTTTM: number;
//     EbtPerEbitTTM: number;
//     EbitPerRevenueTTM: number;
//     DebtRatioTTM: number;
//     DebtEquityRatioTTM: number;
//     LongTermDebtToCapitalizationTTM: number;
//     TotalDebtToCapitalizationTTM: number;
//     InterestCoverageTTM: number;
//     CashFlowToDebtRatioTTM: number;
//     CompanyEquityMultiplierTTM: number;
//     ReceivablesTurnoverTTM: number;
//     PayablesTurnoverTTM: number;
//     InventoryTurnoverTTM: number;
//     FixedAssetTurnoverTTM: number;
//     AssetTurnoverTTM: number;
//     OperatingCashFlowPerShareTTM: number;
//     FreeCashFlowPerShareTTM: number;
//     CashPerShareTTM: number;
//     OperatingCashFlowSalesRatioTTM: number;
//     FreeCashFlowOperatingCashFlowRatioTTM: number;
//     CashFlowCoverageRatiosTTM: number;
//     ShortTermCoverageRatiosTTM: number;
//     CapitalExpenditureCoverageRatioTTM: number;
//     DividendPaidAndCapexCoverageRatioTTM: number;
//     PriceBookValueRatioTTM: number;
//     PriceToBookRatioTTM: number;
//     PriceToSalesRatioTTM: number;
//     PriceEarningsRatioTTM: number;
//     PriceToFreeCashFlowsRatioTTM: number;
//     PriceToOperatingCashFlowsRatioTTM: number;
//     PriceCashFlowRatioTTM: number;
//     PriceEarningsToGrowthRatioTTM: number;
//     PriceSalesRatioTTM: number;
//     DividendYieldTTM: number;
//     EnterpriseValueMultipleTTM: number;
//     PriceFairValueTTM: number;
//     DividendPerShareTTM: number;
// }

// export interface CompanyIncomeStatement {
//     Date: string;
//     Symbol: string;
//     ReportedCurrency: string;
//     Cik: string;
//     FillingDate: string;
//     AcceptedDate: string;
//     CalendarYear: string;
//     Period: string;
//     Revenue: number;
//     CostOfRevenue: number;
//     GrossProfit: number;
//     GrossProfitRatio: number;
//     ResearchAndDevelopmentExpenses: number;
//     GeneralAndAdministrativeExpenses: number;
//     SellingAndMarketingExpenses: number;
//     SellingGeneralAndAdministrativeExpenses: number;
//     OtherExpenses: number;
//     OperatingExpenses: number;
//     CostAndExpenses: number;
//     InterestIncome: number;
//     InterestExpense: number;
//     DepreciationAndAmortization: number;
//     Ebitda: number;
//     EbitdaRatio: number;
//     OperatingIncome: number;
//     OperatingIncomeRatio: number;
//     TotalOtherIncomeExpensesNet: number;
//     IncomeBeforeTax: number;
//     IncomeBeforeTaxRatio: number;
//     IncomeTaxExpense: number;
//     NetIncome: number;
//     NetIncomeRatio: number;
//     Eps: number;
//     EpsDiluted: number;
//     WeightedAverageShsOut: number;
//     WeightedAverageShsOutDil: number;
//     Link: string;
//     FinalLink: string;
// }

// export interface CompanyBalanceSheet {
//     Date: string;
//     Symbol: string;
//     ReportedCurrency: string;
//     Cik: string;
//     FillingDate: string;
//     AcceptedDate: string;
//     CalendarYear: string;
//     Period: string;
//     CashAndCashEquivalents: number;
//     ShortTermInvestments: number;
//     CashAndShortTermInvestments: number;
//     NetReceivables: number;
//     Inventory: number;
//     OtherCurrentAssets: number;
//     TotalCurrentAssets: number;
//     PropertyPlantEquipmentNet: number;
//     Goodwill: number;
//     IntangibleAssets: number;
//     GoodwillAndIntangibleAssets: number;
//     LongTermInvestments: number;
//     TaxAssets: number;
//     OtherNonCurrentAssets: number;
//     TotalNonCurrentAssets: number;
//     OtherAssets: number;
//     TotalAssets: number;
//     AccountPayables: number;
//     ShortTermDebt: number;
//     TaxPayables: number;
//     DeferredRevenue: number;
//     OtherCurrentLiabilities: number;
//     TotalCurrentLiabilities: number;
//     LongTermDebt: number;
//     DeferredRevenueNonCurrent: number;
//     DeferredTaxLiabilitiesNonCurrent: number;
//     OtherNonCurrentLiabilities: number;
//     TotalNonCurrentLiabilities: number;
//     OtherLiabilities: number;
//     CapitalLeaseObligations: number;
//     TotalLiabilities: number;
//     PreferredStock: number;
//     CommonStock: number;
//     RetainedEarnings: number;
//     AccumulatedOtherComprehensiveIncomeLoss: number;
//     OtherTotalStockholdersEquity: number;
//     TotalStockholdersEquity: number;
//     TotalEquity: number;
//     TotalLiabilitiesAndStockholdersEquity: number;
//     MinorityInterest: number;
//     TotalLiabilitiesAndTotalEquity: number;
//     TotalInvestments: number;
//     TotalDebt: number;
//     NetDebt: number;
//     Link: string;
//     FinalLink: string;
// }

// export interface CompanyCashFlow {
//     Date: string;
//     Symbol: string;
//     ReportedCurrency: string;
//     Cik: string;
//     FillingDate: string;
//     AcceptedDate: string;
//     CalendarYear: string;
//     Period: string;
//     NetIncome: number;
//     DepreciationAndAmortization: number;
//     DeferredIncomeTax: number;
//     StockBasedCompensation: number;
//     ChangeInWorkingCapital: number;
//     AccountsReceivables: number;
//     Inventory: number;
//     AccountsPayables: number;
//     OtherWorkingCapital: number;
//     OtherNonCashItems: number;
//     NetCashProvidedByOperatingActivities: number;
//     InvestmentsInPropertyPlantAndEquipment: number;
//     AcquisitionsNet: number;
//     PurchasesOfInvestments: number;
//     SalesMaturitiesOfInvestments: number;
//     OtherInvestingActivites: number;
//     NetCashUsedForInvestingActivites: number;
//     DebtRepayment: number;
//     CommonStockIssued: number;
//     CommonStockRepurchased: number;
//     DividendsPaid: number;
//     OtherFinancingActivites: number;
//     NetCashUsedProvidedByFinancingActivities: number;
//     EffectOfForexChangesOnCash: number;
//     NetChangeInCash: number;
//     CashAtEndOfPeriod: number;
//     CashAtBeginningOfPeriod: number;
//     OperatingCashFlow: number;
//     CapitalExpenditure: number;
//     FreeCashFlow: number;
//     Link: string;
//     FinalLink: string;
// }

// export interface CompanyKeyMetrics {
//     RevenuePerShareTTM: number;
//     NetIncomePerShareTTM: number;
//     OperatingCashFlowPerShareTTM: number;
//     FreeCashFlowPerShareTTM: number;
//     CashPerShareTTM: number;
//     BookValuePerShareTTM: number;
//     TangibleBookValuePerShareTTM: number;
//     ShareholdersEquityPerShareTTM: number;
//     InterestDebtPerShareTTM: number;
//     MarketCapTTM: number;
//     EnterpriseValueTTM: number;
//     PeRatioTTM: number;
//     PriceToSalesRatioTTM: number;
//     PocfRatioTTM: number;
//     PfcfRatioTTM: number;
//     PbRatioTTM: number;
//     PtbRatioTTM: number;
//     EvToSalesTTM: number;
//     EnterpriseValueOverEBITDATTM: number;
//     EvToOperatingCashFlowTTM: number;
//     EvToFreeCashFlowTTM: number;
//     EarningsYieldTTM: number;
//     FreeCashFlowYieldTTM: number;
//     DebtToEquityTTM: number;
//     DebtToAssetsTTM: number;
//     NetDebtToEBITDATTM: number;
//     CurrentRatioTTM: number;
//     InterestCoverageTTM: number;
//     IncomeQualityTTM: number;
//     DividendYieldTTM: number;
//     DividendYieldPercentageTTM: number;
//     PayoutRatioTTM: number;
//     SalesGeneralAndAdministrativeToRevenueTTM: number;
//     ResearchAndDevelopementToRevenueTTM: number;
//     IntangiblesToTotalAssetsTTM: number;
//     CapexToOperatingCashFlowTTM: number;
//     CapexToRevenueTTM: number;
//     CapexToDepreciationTTM: number;
//     StockBasedCompensationToRevenueTTM: number;
//     GrahamNumberTTM: number;
//     RoicTTM: number;
//     ReturnOnTangibleAssetsTTM: number;
//     GrahamNetNetTTM: number;
//     WorkingCapitalTTM: number;
//     TangibleAssetValueTTM: number;
//     NetCurrentAssetValueTTM: number;
//     InvestedCapitalTTM: number;
//     AverageReceivablesTTM: number;
//     AveragePayablesTTM: number;
//     AverageInventoryTTM: number;
//     DaysSalesOutstandingTTM: number;
//     DaysPayablesOutstandingTTM: number;
//     DaysOfInventoryOnHandTTM: number;
//     ReceivablesTurnoverTTM: number;
//     PayablesTurnoverTTM: number;
//     InventoryTurnoverTTM: number;
//     RoeTTM: number;
//     CapexPerShareTTM: number;
//     DividendPerShareTTM: number;
//     DebtToMarketCapTTM: number;
// }

// export interface CompanyHistoricalDividend {
//     Symbol: string;
//     Historical: Dividend[];
// }

// export interface Dividend {
//     Date: string;
//     Label: string;
//     AdjDividend: number;
//     Dividend: number;
//     RecordDate: string;
//     PaymentDate: string;
//     DeclarationDate: string;
// }

// export interface CompanyCompData {
//     Symbol: string;
//     PeersList: string[];
// }

// export interface CompanyTenK {
//     Symbol: string;
//     FillingDate: string;
//     AcceptedDate: string;
//     Cik: string;
//     Type: string;
//     Link: string;
//     FinalLink: string;
// }

export interface CompanySearch {
    currency: string;
    exchangeShortName: string;
    name: string;
    stockExchange: string;
    symbol: string;
}

export interface CompanyProfile {
    symbol: string;
    price: number;
    beta: number;
    volAvg: number;
    mktCap: number;
    lastDiv: number;
    range: string;
    changes: number;
    companyName: string;
    currency: string;
    cik: string;
    isin: string;
    exchange: string;
    exchangeShortName: string;
    industry: string;
    website: string;
    description: string;
    ceo: string;
    sector: string;
    counter: string;
    fullTimeEmployees: string;
    phone: string;
    address: string;
    city: string;
    state: string;
    zip: string;
    dcfDiff: number;
    dcf: number;
    image: string;
    ipoDate: string;
    defaultImage: boolean;
    isEtf: boolean;
    isActivelyTrading: boolean;
    isAdr: boolean;
    isFund: boolean;
}

export interface CompanyKeyRatios {
    dividendYielTTM: number;
    dividendYielPercentageTTM: number;
    peRatioTTM: number;
    pegRatioTTM: number;
    payoutRatioTTM: number;
    currentRatioTTM: number;
    quickRatioTTM: number;
    cashRatioTTM: number;
    daysOfSalesOutstandingTTM: number;
    daysOfInventoryOutstandingTTM: number;
    operatingCycleTTM: number;
    daysOfPayablesOutstandingTTM: number;
    cashConversionCycleTTM: number;
    grossProfitMarginTTM: number;
    operatingProfitMarginTTM: number;
    pretaxProfitMarginTTM: number;
    netProfitMarginTTM: number;
    effectiveTaxRateTTM: number;
    returnOnAssetsTTM: number;
    returnOnEquityTTM: number;
    returnOnCapitalEmployedTTM: number;
    netIncomePerEBTTTM: number;
    ebtPerEbitTTM: number;
    ebitPerRevenueTTM: number;
    debtRatioTTM: number;
    debtEquityRatioTTM: number;
    longTermDebtToCapitalizationTTM: number;
    totalDebtToCapitalizationTTM: number;
    interestCoverageTTM: number;
    cashFlowToDebtRatioTTM: number;
    companyEquityMultiplierTTM: number;
    receivablesTurnoverTTM: number;
    payablesTurnoverTTM: number;
    inventoryTurnoverTTM: number;
    fixedAssetTurnoverTTM: number;
    assetTurnoverTTM: number;
    operatingCashFlowPerShareTTM: number;
    freeCashFlowPerShareTTM: number;
    cashPerShareTTM: number;
    operatingCashFlowSalesRatioTTM: number;
    freeCashFlowOperatingCashFlowRatioTTM: number;
    cashFlowCoverageRatiosTTM: number;
    shortTermCoverageRatiosTTM: number;
    capitalExpenditureCoverageRatioTTM: number;
    dividendPaidAndCapexCoverageRatioTTM: number;
    priceBookValueRatioTTM: number;
    priceToBookRatioTTM: number;
    priceToSalesRatioTTM: number;
    priceEarningsRatioTTM: number;
    priceToFreeCashFlowsRatioTTM: number;
    priceToOperatingCashFlowsRatioTTM: number;
    priceCashFlowRatioTTM: number;
    priceEarningsToGrowthRatioTTM: number;
    priceSalesRatioTTM: number;
    dividendYieldTTM: number;
    enterpriseValueMultipleTTM: number;
    priceFairValueTTM: number;
    dividendPerShareTTM: number;
}

export interface CompanyIncomeStatement {
    date: string;
    symbol: string;
    reportedCurrency: string;
    cik: string;
    fillingDate: string;
    acceptedDate: string;
    calendarYear: string;
    period: string;
    revenue: number;
    costOfRevenue: number;
    grossProfit: number;
    grossProfitRatio: number;
    researchAndDevelopmentExpenses: number;
    generalAndAdministrativeExpenses: number;
    sellingAndMarketingExpenses: number;
    sellingGeneralAndAdministrativeExpenses: number;
    otherExpenses: number;
    operatingExpenses: number;
    costAndExpenses: number;
    interestIncome: number;
    interestExpense: number;
    depreciationAndAmortization: number;
    ebitda: number;
    ebitdaratio: number;
    operatingIncome: number;
    operatingIncomeRatio: number;
    totalOtherIncomeExpensesNet: number;
    incomeBeforeTax: number;
    incomeBeforeTaxRatio: number;
    incomeTaxExpense: number;
    netIncome: number;
    netIncomeRatio: number;
    eps: number;
    epsdiluted: number;
    weightedAverageShsOut: number;
    weightedAverageShsOutDil: number;
    link: string;
    finalLink: string;
}

export interface CompanyBalanceSheet {
    date: string;
    symbol: string;
    reportedCurrency: string;
    cik: string;
    fillingDate: string;
    acceptedDate: string;
    calendarYear: string;
    period: string;
    cashAndCashEquivalents: number;
    shortTermInvestments: number;
    cashAndShortTermInvestments: number;
    netReceivables: number;
    inventory: number;
    otherCurrentAssets: number;
    totalCurrentAssets: number;
    propertyPlantEquipmentNet: number;
    goodwill: number;
    intangibleAssets: number;
    goodwillAndIntangibleAssets: number;
    longTermInvestments: number;
    taxAssets: number;
    otherNonCurrentAssets: number;
    totalNonCurrentAssets: number;
    otherAssets: number;
    totalAssets: number;
    accountPayables: number;
    shortTermDebt: number;
    taxPayables: number;
    deferredRevenue: number;
    otherCurrentLiabilities: number;
    totalCurrentLiabilities: number;
    longTermDebt: number;
    deferredRevenueNonCurrent: number;
    deferredTaxLiabilitiesNonCurrent: number;
    otherNonCurrentLiabilities: number;
    totalNonCurrentLiabilities: number;
    otherLiabilities: number;
    capitalLeaseObligations: number;
    totalLiabilities: number;
    preferredStock: number;
    commonStock: number;
    retainedEarnings: number;
    accumulatedOtherComprehensiveIncomeLoss: number;
    othertotalStockholdersEquity: number;
    totalStockholdersEquity: number;
    totalEquity: number;
    totalLiabilitiesAndStockholdersEquity: number;
    minorityInterest: number;
    totalLiabilitiesAndTotalEquity: number;
    totalInvestments: number;
    totalDebt: number;
    netDebt: number;
    link: string;
    finalLink: string;
}

export interface CompanyCashFlow {
    date: string;
    symbol: string;
    reportedCurrency: string;
    cik: string;
    fillingDate: string;
    acceptedDate: string;
    calendarYear: string;
    period: string;
    netIncome: number;
    depreciationAndAmortization: number;
    deferredIncomeTax: number;
    stockBasedCompensation: number;
    changeInWorkingCapital: number;
    accountsReceivables: number;
    inventory: number;
    accountsPayables: number;
    otherWorkingCapital: number;
    otherNonCashItems: number;
    netCashProvidedByOperatingActivities: number;
    investmentsInPropertyPlantAndEquipment: number;
    acquisitionsNet: number;
    purchasesOfInvestments: number;
    salesMaturitiesOfInvestments: number;
    otherInvestingActivites: number;
    netCashUsedForInvestingActivites: number;
    debtRepayment: number;
    commonStockIssued: number;
    commonStockRepurchased: number;
    dividendsPaid: number;
    otherFinancingActivites: number;
    netCashUsedProvidedByFinancingActivities: number;
    effectOfForexChangesOnCash: number;
    netChangeInCash: number;
    cashAtEndOfPeriod: number;
    cashAtBeginningOfPeriod: number;
    operatingCashFlow: number;
    capitalExpenditure: number;
    freeCashFlow: number;
    link: string;
    finalLink: string;
}

export interface CompanyKeyMetrics {
    revenuePerShareTTM: number;
    netIncomePerShareTTM: number;
    operatingCashFlowPerShareTTM: number;
    freeCashFlowPerShareTTM: number;
    cashPerShareTTM: number;
    bookValuePerShareTTM: number;
    tangibleBookValuePerShareTTM: number;
    shareholdersEquityPerShareTTM: number;
    interestDebtPerShareTTM: number;
    marketCapTTM: number;
    enterpriseValueTTM: number;
    peRatioTTM: number;
    priceToSalesRatioTTM: number;
    pocfratioTTM: number;
    pfcfRatioTTM: number;
    pbRatioTTM: number;
    ptbRatioTTM: number;
    evToSalesTTM: number;
    enterpriseValueOverEBITDATTM: number;
    evToOperatingCashFlowTTM: number;
    evToFreeCashFlowTTM: number;
    earningsYieldTTM: number;
    freeCashFlowYieldTTM: number;
    debtToEquityTTM: number;
    debtToAssetsTTM: number;
    netDebtToEBITDATTM: number;
    currentRatioTTM: number;
    interestCoverageTTM: number;
    incomeQualityTTM: number;
    dividendYieldTTM: number;
    dividendYieldPercentageTTM: number;
    payoutRatioTTM: number;
    salesGeneralAndAdministrativeToRevenueTTM: number;
    researchAndDevelopementToRevenueTTM: number;
    intangiblesToTotalAssetsTTM: number;
    capexToOperatingCashFlowTTM: number;
    capexToRevenueTTM: number;
    capexToDepreciationTTM: number;
    stockBasedCompensationToRevenueTTM: number;
    grahamNumberTTM: number;
    roicTTM: number;
    returnOnTangibleAssetsTTM: number;
    grahamNetNetTTM: number;
    workingCapitalTTM: number;
    tangibleAssetValueTTM: number;
    netCurrentAssetValueTTM: number;
    investedCapitalTTM: number;
    averageReceivablesTTM: number;
    averagePayablesTTM: number;
    averageInventoryTTM: number;
    daysSalesOutstandingTTM: number;
    daysPayablesOutstandingTTM: number;
    daysOfInventoryOnHandTTM: number;
    receivablesTurnoverTTM: number;
    payablesTurnoverTTM: number;
    inventoryTurnoverTTM: number;
    roeTTM: number;
    capexPerShareTTM: number;
    dividendPerShareTTM: number;
    debtToMarketCapTTM: number;
}

export interface CompanyHistoricalDividend {
    symbol: string;
    historical: Dividend[];
}

export interface Dividend {
    date: string;
    label: string;
    adjDividend: number;
    dividend: number;
    recordDate: string;
    paymentDate: string;
    declarationDate: string;
}

export interface CompanyCompData {
    symbol: string;
    peersList: string[];
}

export interface CompanyTenK {
    symbol: string;
    fillingDate: string;
    acceptedDate: string;
    cik: string;
    type: string;
    link: string;
    finalLink: string;
}